
name: Deploy to Azure Function (Staging)

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

env:
  TFSTATE_RG: ${{vars.TFSTATE_RG}}
  STORAGEACCOUNTNAME: ${{vars.STORAGEACCOUNTNAME}}
  CONTAINERNAME: ${{vars.CONTAINERNAME}}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID:  ${{ secrets.AZURE_TENANT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        working-directory: infra
        run: |
          terraform init \
          -backend-config="resource_group_name=${{ env.TFSTATE_RG }}" \
          -backend-config="storage_account_name=${{ env.STORAGEACCOUNTNAME }}" \
          -backend-config="container_name=${{ env.CONTAINERNAME }}" 

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve

      - name: Build Go App
        run: GOOS=linux GOARCH=amd64 go build handler.go
      - name: Setup Func core tools
        run: |
          sudo apt-get update
          sudo apt-get install azure-functions-core-tools-4
      - name: Deploy to function
        run: |
          func --version
          $env:CLI_DEBUG=1 
          func azure functionapp publish jeffs-go-lang --custom
      # - name: Swap Slot to function
      #   run: |
      #     az functionapp deployment slot swap --slot stage -g example-resources -n jeffs-go-lang

      # - name: Deploy to Azure Function
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: jeffs-go-lang
      #     slot-name: stage
      #     publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE }}
      #     package: ./app
