
name: Deploy to Azure Function (Staging)

on: workflow_dispatch
 
permissions:
  id-token: write
  contents: read

env:
  TFSTATE_RG: ${{vars.TFSTATE_RG}}
  STORAGEACCOUNTNAME: ${{vars.STORAGEACCOUNTNAME}}
  CONTAINERNAME: ${{vars.CONTAINERNAME}}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID:  ${{ secrets.AZURE_TENANT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        working-directory: infra
        run: |
          terraform init \
          -backend-config="resource_group_name=${{ env.TFSTATE_RG }}" \
          -backend-config="storage_account_name=${{ env.STORAGEACCOUNTNAME }}" \
          -backend-config="container_name=${{ env.CONTAINERNAME }}" 

      - name: Terraform Apply
        working-directory: infra
        run: terraform destroy -auto-approve